---
title: "migrate_ind_ff2.0_fish"
author: "Mariano Viz"
date: "2024-07-19"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)

library(mermaidr)
library(tidyverse)
library(here)
library(lubridate)
library(kableExtra)
library(stringdist)
library(writexl)
library(readxl)
library(geosphere)


```



# Migrating Sites

### Read in Sites and adressing missing sites' reef type, zone, and exposure 

```{r}
# NEED TO CHECK W/GEORGE IF THIS APPROACH MAKES ANY SENSE!!! 

# Read in the fish sites data
fish_sites <- read_excel(here("data", "processed", "indonesia", "ff2.0", "ind_ff2.0_fish_sites_processed.xlsx"))

# Convert "NA" strings to actual NA values for character and factor columns
fish_sites <- fish_sites %>%
  mutate(across(where(is.character), ~ na_if(., "NA")))

# Function to fill NAs based on the closest latitude and longitude
fill_na_with_closest <- function(data, lat_col, lon_col, target_cols) {
  for (col in target_cols) {
    for (i in 1:nrow(data)) {
      if (is.na(data[[i, col]])) {
        current_lat <- data[[i, lat_col]]
        current_lon <- data[[i, lon_col]]

        # Filter to only rows where the target column is not NA
        non_na_rows <- data[!is.na(data[[col]]), ]

        if (nrow(non_na_rows) > 0) {
          # Calculate distances to all non-NA points
          distances <- distVincentySphere(
            cbind(non_na_rows[[lon_col]], non_na_rows[[lat_col]]),
            matrix(c(current_lon, current_lat), nrow = 1)
          )

          closest_idx <- which.min(distances)

          if (!is.infinite(distances[closest_idx])) {
            data[[i, col]] <- non_na_rows[[closest_idx, col]]
          }

          # Debugging information
          cat("Row:", i, "Column:", col, "Closest idx:", closest_idx, "Distance:", distances[closest_idx], "\n")
        }
      }
    }
  }
  return(data)
}

# Columns to fill
columns_to_fill <- c("reef_type", "reef_zone", "reef_exposure")

# Apply the function to fill NAs in the specified columns
fish_sites <- fill_na_with_closest(fish_sites, "latitude", "longitude", columns_to_fill)


```




```{r}

# Get project for import
project <- mermaid_search_my_projects("indonesia_ff2.0_fish", include_test_projects = TRUE)

# Sites
# Example
  #sites <- tribble(
    #~name, ~latitude, ~longitude, ~notes, ~country, ~reef_type, ~reef_zone, ~exposure,
    #"Test site 1", 43.65107, -79.347015, NA, "Canada", "fringing", "crest", "semi-exposed",
    #"Test site 2", 43.65507, -79.347015, NA, "Canada", "fringing", "crest", "semi-exposedd"
  #)

fish_sites <- fish_sites %>%
  select(name, latitude, longitude, country, reef_type, reef_zone, reef_exposure) %>%
  mutate(notes = NA) %>%
  rename(exposure = reef_exposure)

# Try to import
# Access docs via ?mermaid_import_project_sites
fish_sites %>%
  mermaid_import_project_sites(project)



# Management regimes --> Manually (only 2 Management Regimes)!!
#Example
  #management_regimes <- tribble(
    #~name, ~est_year, ~size, ~parties, ~compliance, ~access_restriction, ~periodic_closure,
    #"Reserve", NA, NA, "community/local government; NGO", "full", TRUE, TRUE,
    #"Managed Access", NA, NA, "community/local government; NGO", "full", TRUE, TRUE,
  #)

# Try to import
# Access docs via ?mermaid_import_project_managements
  #management_regimes %>%
    #mermaid_import_project_managements(project)

```


# Migrating Data


### 1. Download the MERMAID Template

```{r}

# Access your MERMAID projects by using mermaid_search_my_projects() with the project name
project <- mermaid_search_my_projects("indonesia_ff2.0_fish", include_test_projects = TRUE)

# Get the fish belt MERMAID template and options using mermaid_import_get_template_and_options() and save it to a file (in this case called fishbelt_mermaid_template.xlsx and benthicpit_mermaid_template.xlsx)
fish_template_and_options <- mermaid_import_get_template_and_options( 
  project,
  "fishbelt",
  "fishbelt_mermaid_template.xlsx")

```

### 2. Reformat the data to match the template

```{r}
# Reading ind_ff2.0_fish_processed.xlsx
fish_data <- read_excel(here("data", "processed", "indonesia", "ff2.0", "ind_ff2.0_fish_processed.xlsx"))


# Update sites to lowercase for fish and convert "Transect number *" to numeric
fish_data <- fish_data %>%
  mutate(
    `Site *` = str_replace_all(str_to_lower(`Site *`), " ", "_"),
    `Transect number *` = as.numeric(`Transect number *`)
  )

```


### 3. Address errors and warnings


```{r}
mermaid_import_check_options(fish_data, fish_template_and_options, "Site *")

mermaid_import_check_options(fish_data, fish_template_and_options, "Management *")

mermaid_import_check_options(fish_data, fish_template_and_options, "Sample date: Year *")

mermaid_import_check_options(fish_data, fish_template_and_options, "Sample date: Month *")

mermaid_import_check_options(fish_data, fish_template_and_options,"Sample date: Day *")

mermaid_import_check_options(fish_data, fish_template_and_options,"Depth *")
         
mermaid_import_check_options(fish_data, fish_template_and_options,"Transect number *")
         
mermaid_import_check_options(fish_data, fish_template_and_options,"Transect length surveyed *")
         
mermaid_import_check_options(fish_data, fish_template_and_options,"Width *")
        
mermaid_import_check_options(fish_data, fish_template_and_options,"Fish size bin *")
         
mermaid_import_check_options(fish_data, fish_template_and_options,"Observer emails *")
         
mermaid_import_check_options(fish_data, fish_template_and_options,"Fish name *")
 
  # Renaming Fish Species
 fish_data <- fish_data %>% 
   mutate(`Fish name *` = case_when(
    `Fish name *` == "Acanthurus spp." ~ "Acanthurus mata",
    `Fish name *` == "Scarus spp." ~ "Scarus iseri",
        `Fish name *` == "Pterocaesio spp." ~ "Pterocaesio tile",
    `Fish name *` == "Lethrinus spp." ~ "Lethrinus",
        `Fish name *` == "" ~ "",
    `Fish name *` == "Naso spp." ~ "Naso",
    `Fish name *` == "Siganus spp." ~ "Siganus uspi",
        `Fish name *` == "Balistoides spp." ~ "Balistoides",
    `Fish name *` == "Platax spp." ~ "Platax",
        `Fish name *` == "Lutjanus spp." ~ "Lutjanus jocu",
        `Fish name *` == "Plectropomus spp." ~ "Plectropomus",
    `Fish name *` == "Epinephelus spp." ~ "Epinephelus",
        `Fish name *` == "Caesio spp." ~ "Caesio",
        `Fish name *` == "Cephalopholis spp." ~ "Cephalopholis",
       `Fish name *` == "Plectorhinchus spp." ~ "Plectorhinchus",
    `Fish name *` == "" ~ "",
    TRUE ~ `Fish name *`
  ))


mermaid_import_check_options(fish_data, fish_template_and_options,"Size *")
         
mermaid_import_check_options(fish_data, fish_template_and_options,"Count *")


# Clean Data

write_csv(fish_data, "fishbelt_clean.csv")

```

### 4. Import (ingest) data to MERMAID


```{r}
# “Dry run” before actually ingesting to check the data:
mermaid_import_project_data(
  fish_data,
  project,
  method = "fishbelt",
  dryrun = TRUE
)


# Ingesting data:
mermaid_import_project_data(
  fish_data,
  project,
  method = "fishbelt",
  dryrun = FALSE
)


```








