---
title: "migrate_ind_ff2.0_habitat"
author: "Mariano Viz"
date: "2024-07-19"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)

library(mermaidr)
library(tidyverse)
library(here)
library(lubridate)
library(kableExtra)
library(stringdist)
library(writexl)
library(readxl)
library(geosphere)

```


# Migrating Sites

# Read in Sites and adressing missing sites' reef type, zone, and exposure 

```{r}
# NEED TO CHECK W/GEORGE IF THIS APPROACH MAKES ANY SENSE!!! 

# Read in the habitat sites data
habitat_sites <- read_excel(here("data", "processed", "indonesia", "ff2.0", "ind_ff2.0_habitat_sites_processed.xlsx"))

# Convert "NA" strings to actual NA values for character and factor columns
habitat_sites <- habitat_sites %>%
  mutate(across(where(is.character), ~ na_if(., "NA")))

# Function to fill NAs based on the closest latitude and longitude
fill_na_with_closest <- function(data, lat_col, lon_col, target_cols) {
  for (col in target_cols) {
    for (i in 1:nrow(data)) {
      if (is.na(data[[i, col]])) {
        current_lat <- data[[i, lat_col]]
        current_lon <- data[[i, lon_col]]

        # Filter to only rows where the target column is not NA
        non_na_rows <- data[!is.na(data[[col]]), ]

        if (nrow(non_na_rows) > 0) {
          # Calculate distances to all non-NA points
          distances <- distVincentySphere(
            cbind(non_na_rows[[lon_col]], non_na_rows[[lat_col]]),
            matrix(c(current_lon, current_lat), nrow = 1)
          )

          closest_idx <- which.min(distances)

          if (!is.infinite(distances[closest_idx])) {
            data[[i, col]] <- non_na_rows[[closest_idx, col]]
          }

          # Debugging information
          cat("Row:", i, "Column:", col, "Closest idx:", closest_idx, "Distance:", distances[closest_idx], "\n")
        }
      }
    }
  }
  return(data)
}

# Columns to fill
columns_to_fill <- c("reef_type", "reef_zone", "reef_exposure")

# Apply the function to fill NAs in the specified columns
habitat_sites <- fill_na_with_closest(habitat_sites, "latitude", "longitude", columns_to_fill)


```



```{r}

# Get project for import
project <- mermaid_search_my_projects("indonesia_ff2.0_habitat", include_test_projects = TRUE)

# Sites
# Example
  #sites <- tribble(
    #~name, ~latitude, ~longitude, ~notes, ~country, ~reef_type, ~reef_zone, ~exposure,
    #"Test site 1", 43.65107, -79.347015, NA, "Canada", "fringing", "crest", "semi-exposed",
    #"Test site 2", 43.65507, -79.347015, NA, "Canada", "fringing", "crest", "semi-exposedd"
  #)

habitat_sites <- habitat_sites %>%
  select(name, latitude, longitude, country, reef_type, reef_zone, reef_exposure) %>%
  mutate(notes = NA) %>%
  rename(exposure = reef_exposure)

# Try to import
# Access docs via ?mermaid_import_project_sites
habitat_sites %>%
  mermaid_import_project_sites(project)



# Management regimes --> Manually (only 2 Management Regimes)!!
#Example
  #management_regimes <- tribble(
    #~name, ~est_year, ~size, ~parties, ~compliance, ~access_restriction, ~periodic_closure,
    #"Reserve", NA, NA, "community/local government; NGO", "full", TRUE, TRUE,
    #"Managed Access", NA, NA, "community/local government; NGO", "full", TRUE, TRUE,
  #)

# Try to import
# Access docs via ?mermaid_import_project_managements
  #management_regimes %>%
    #mermaid_import_project_managements(project)

```



# Migrating Data


### 1. Download the MERMAID Template

```{r}

# Access your MERMAID projects by using mermaid_search_my_projects() with the project name
project <- mermaid_search_my_projects("indonesia_ff2.0_habitat", include_test_projects = TRUE)

# Get the fish belt MERMAID template and options using mermaid_import_get_template_and_options() and save it to a file (in this case called fishbelt_mermaid_template.xlsx and benthicpit_mermaid_template.xlsx)
habitat_pit_template_and_options <- mermaid_import_get_template_and_options(
  project,
  "benthicpit", # Method
  "benthicpit_mermaid_template.xlsx")

habitat_pit_template_and_options[["Template"]]
names(habitat_pit_template_and_options)
habitat_pit_template_and_options[["Interval start *"]] 
habitat_pit_template_and_options[["Transect length surveyed *"]]
habitat_pit_template_and_options[["Interval size *"]]
habitat_pit_template_and_options[["Observation interval *"]] 

```

### 2. Reformat the data to match the template

```{r}
# Reading ind_ff2.0_habitat_processed.xlsx
habitat_data <- read_excel(here("data", "processed", "indonesia", "ff2.0", "ind_ff2.0_habitat_processed.xlsx"))


# Update sites to lowercase for habitat
habitat_data <- habitat_data %>%
  mutate(`Site *` = str_replace_all(str_to_lower(`Site *`), " ", "_"))

# Replace NAs in Depth
# Calculate the average depth, ignoring NA values, and round to the nearest integer
average_depth <- habitat_data %>%
  filter(!is.na(`Depth *`)) %>%
  summarize(avg_depth = round(mean(as.numeric(`Depth *`), na.rm = TRUE))) %>%
  pull(avg_depth)

# Replace NA values in "Depth *" with the calculated average depth
habitat_data <- habitat_data %>%
  mutate(`Depth *` = ifelse(is.na(`Depth *`), average_depth, `Depth *`))

# Add a new column "Interval start *", "Transect length surveyed *", "Interval size *", "Observation interval *", and "Observer emails *" 
habitat_data <- habitat_data %>%
  mutate(`Interval start *` = 0.5,
         `Transect length surveyed *` = 50,
         `Interval size *` = 0.5,
         `Observation interval *` = 0.5, # CHECK THIS NUMBERS!! (FF Methodology p. 12; Ahmadia et al. (2013) p. 28)
         `Observer emails *` = "marianoviz1988@gmail.com")

```


### 3. Address errors and warnings


```{r}
mermaid_import_check_options(habitat_data, habitat_pit_template_and_options, "Site *")

mermaid_import_check_options(habitat_data, habitat_pit_template_and_options, "Management *")

mermaid_import_check_options(habitat_data, habitat_pit_template_and_options, "Sample date: Year *")

mermaid_import_check_options(habitat_data, habitat_pit_template_and_options, "Sample date: Month *")

mermaid_import_check_options(habitat_data, habitat_pit_template_and_options,"Sample date: Day *")

mermaid_import_check_options(habitat_data, habitat_pit_template_and_options,"Interval start *")

mermaid_import_check_options(habitat_data, habitat_pit_template_and_options,"Benthic attribute *") 


# Manually changing Benthic Attributes:
  
  # Define the path to the uploaded file
  file_path <- here("src", "data_migration", "indonesia", "ff2.0", "benthicpit_mermaid_template.xlsx")
  
  # Read the "Benthic attribute" sheet without using the first row as column names
  benthic_attribute_data <- read_excel(file_path, sheet = "Benthic attribute", col_names = FALSE)
  
  # Rename the column to "benthic_attribute"
  colnames(benthic_attribute_data) <- "benthic_attribute"
  
  # List of valid benthic attributes
  valid_benthic_attributes <- benthic_attribute_data$benthic_attribute
  
  # Function to replace non-matching values with the closest match
  replace_with_closest_match <- function(value, valid_values) {
    if (value %in% valid_values) {
      return(value)
    } else {
      closest_match <- valid_values[which.min(stringdist::stringdist(value, valid_values))]
      return(closest_match)
    }
  }
  
  # Apply the function to the "Benthic attribute *" column
  habitat_data <- habitat_data %>%
    mutate(`Benthic attribute *` = map_chr(`Benthic attribute *`, ~replace_with_closest_match(.x, valid_benthic_attributes)))



mermaid_import_check_options(habitat_data, habitat_pit_template_and_options,"Transect length surveyed *")

mermaid_import_check_options(habitat_data, habitat_pit_template_and_options,"Depth *")

mermaid_import_check_options(habitat_data, habitat_pit_template_and_options,"Observer emails *")

mermaid_import_check_options(habitat_data, habitat_pit_template_and_options,"Interval size *")
         
mermaid_import_check_options(habitat_data, habitat_pit_template_and_options,"Transect number *")
        
mermaid_import_check_options(habitat_data, habitat_pit_template_and_options,"Observation interval *")
         

# Clean Data

write_csv(habitat_data, "benthicpit_clean.csv")

```

### 4. Import (ingest) data to MERMAID


```{r}
# “Dry run” before actually ingesting to check the data:
mermaid_import_project_data(
  habitat_data,
  project,
  method = "benthicpit",
  dryrun = TRUE
)


# Ingesting data:
mermaid_import_project_data(
  habitat_data,
  project,
  method = "benthicpit",
  dryrun = FALSE
)


```









