---
title: "process_moz_ff2.0"
author: "Mariano Viz"
date: "2024-07-24"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE, message = FALSE, warning = FALSE)

library(tidyverse)
library(here)
library(lubridate)
library(kableExtra)
library(stringdist)
library(writexl)


#Read in data
  #FF2.0 dataset
  ff2_fish <- read_csv(here("data", "raw", "Mermaid Ingest Data", "Historical","ff2_fish.csv"))
  ff2_habitat <- read_csv(here("data", "raw", "Mermaid Ingest Data","Historical","ff2_habitat.csv"))
  #MERMAID Sites
  sites_mermaid <- read_csv(here("data", "raw", "Mermaid Ingest Data", "fish-surveys-MERMAID.csv"))


```

# Content:

  -  Missing Data on Required Fields
    - FF 2.0 Fish
    - FF 2.0 Habitat
  
  - Sites
    - FF 2.0 Fish
    - FF 2.0 Habitat

## Missing Data on Required Fields

### FF 2.0 Fish

```{r}
## Filter country == "Mozambique"
ff2_fish_moz <- ff2_fish %>%
  filter(country == "Mozambique")

##########

## Reformat the data to match the MERMAID template

# Convert 'survey_date' to Date type
ff2_fish_moz$survey_date <- as.Date(ff2_fish_moz$survey_date)
# Create new columns for year, month, and day
ff2_fish_moz <- ff2_fish_moz %>%
  mutate(`Sample date: Year *` = year(survey_date),
         `Sample date: Month *` = month(survey_date),
         `Sample date: Day *` = day(survey_date))

# Column Fish size bin *
ff2_fish_moz <- ff2_fish_moz %>%
  mutate(`Fish size bin *` = 1)

# Column Size *
ff2_fish_moz <- ff2_fish_moz %>%
  rename(`Size *` = length)

# Column Site *
ff2_fish_moz <- ff2_fish_moz %>%
  rename(`Site *` = location_name)

# Column Depth *
ff2_fish_moz <- ff2_fish_moz %>%
  rename(`Depth *` = water_depth)

# Column Transect length surveyed *
ff2_fish_moz <- ff2_fish_moz %>%
  mutate(`Transect length surveyed *` = 50)

# Column Observer emails * 
ff2_fish_moz <- ff2_fish_moz %>%
  mutate(`Observer emails *` = "marianoviz1988@gmail.com")

# Column Count *
ff2_fish_moz <- ff2_fish_moz %>%
  rename(`Count *` = count)

# Column Management *
ff2_fish_moz <- ff2_fish_moz %>%
  rename(`Management *` = location_status)

# Column Transect number  *
ff2_fish_moz <- ff2_fish_moz %>%
  rename(`Transect number *` = transect_no)

# Column Width *
ff2_fish_moz <- ff2_fish_moz %>%
  mutate(`Width *` = "Mixed: >=10 cm & <35 cm @ 5 m, >=35 cm @ 20 m")

# Column "Fish name *" 
ff2_fish_moz <- ff2_fish_moz %>%
  rename(`Fish name *` = species)

# Column Reef slope
ff2_fish_moz <- ff2_fish_moz %>%
  rename(`Reef slope` = reef_slope)


##########

## NAs counts in required fields:
na_counts_moz <- ff2_fish_moz %>%
  summarise(
    `Management *` = sum(is.na(`Management *`)),
    `Sample date: Year *` = sum(is.na(`Sample date: Year *`)),
    `Sample date: Month *` = sum(is.na(`Sample date: Month *`)),
    `Sample date: Day *` = sum(is.na(`Sample date: Day *`)),
    `Depth *` = sum(is.na(`Depth *`)),
    `Transect number *` = sum(is.na(`Transect number *`)),
    `Transect length surveyed *` = sum(is.na(`Transect length surveyed *`)),
    `Width *` = sum(is.na(`Width *`)),
    `Fish size bin *` = sum(is.na(`Fish size bin *`)),
    `Reef slope` = sum(is.na(`Reef slope`)),
    `Observer emails *` = sum(is.na(`Observer emails *`)),
    `Fish name *` = sum(is.na(`Fish name *`)),
    `Size *` = sum(is.na(`Size *`)),
    `Count *` = sum(is.na(`Count *`))
  )

na_counts_moz %>%
  kable() %>%
  kable_styling(bootstrap_options = "striped", full_width = FALSE)


# Select rows with NA values in any of the specified columns
rows_with_na_moz <- ff2_fish_moz %>%
  filter(is.na(`Management *`) | 
           is.na(`Sample date: Year *`) | 
           is.na(`Sample date: Month *`) | 
           is.na(`Sample date: Day *`) | 
           is.na(`Depth *`) | 
           is.na(`Transect number *`) | 
           is.na(`Transect length surveyed *`) | 
           is.na(`Width *`) | 
           is.na(`Fish size bin *`) | 
           is.na(`Reef slope`) | 
           is.na(`Observer emails *`) | 
           is.na(`Fish name *`) | 
           is.na(`Size *`) | 
           is.na(`Count *`))

# Replace missing value (!!!: check replacing strategy)

  # Calculate the average size for "Amphiprion" fish
average_size_amphiprion <- ff2_fish_moz %>%
  filter(grepl("^Amphiprion", `Fish name *`), !is.na(`Size *`)) %>%
  summarise(average_size = mean(`Size *`)) %>%
  pull(average_size)

  # Replace NA value in "Size *" with this average size
ff2_fish_moz <- ff2_fish_moz %>%
  mutate(`Size *` = ifelse(is.na(`Size *`) & grepl("^Amphiprion", `Fish name *`), average_size_amphiprion, `Size *`))


##########

# Select required fields
selected_ff2_fish_moz <- ff2_fish_moz %>%
  select("Site *",
         "Management *",
         "Sample date: Year *",
         "Sample date: Month *",
         "Sample date: Day *",
         "Depth *",
         "Transect number *",
         "Transect length surveyed *",
         "Width *",
         "Fish size bin *",
         "Reef slope",
         "Observer emails *",
         "Fish name *",
         "Size *",
         "Count *")

# Check for NAs
if (any(is.na(selected_ff2_fish_moz))) {
  cat("There are still NAs present.\n")
} else {
  cat("Great, no NAs left!\n")
}


# Excel Output: 
#folder_path <- here("data", "processed", "mozambique", "ff2.0") #No NAs left --> Processed Folder 
#file_path <- file.path(folder_path, "moz_ff2.0_fish_processed.xlsx")
#write_xlsx(selected_ff2_fish_moz, file_path)

```

### FF 2.0 Habitat

```{r}

# Filter country == "Mozambique"
ff2_habitat_moz <- ff2_habitat %>%
  filter(country == "Mozambique")

##########

#Count methodology 
ff2_habitat_moz_methodology <- ff2_habitat_moz %>%
  count(methodology)




##########

## Reformat the data to match the MERMAID template

# Convert 'survey_date' to Date type
ff2_habitat_moz$surveydate <- as.Date(ff2_habitat_moz$surveydate)
# Create new columns for year, month, and day
ff2_habitat_moz <- ff2_habitat_moz %>%
  mutate(`Sample date: Year *` = year(surveydate),
         `Sample date: Month *` = month(surveydate),
         `Sample date: Day *` = day(surveydate))

# Column Site *
ff2_habitat_moz <- ff2_habitat_moz %>%
  rename(`Site *` = location_name)

# Column Management *
ff2_habitat_moz <- ff2_habitat_moz %>%
  rename(`Management *` = location_status)

# Column Transect number  *
ff2_habitat_moz <- ff2_habitat_moz %>%
  rename(`Transect number *` = transect_no)

# Column Depth *
ff2_habitat_moz <- ff2_habitat_moz %>%
  rename(`Depth *` = depth_m)

# Column Benthic attribute  *
ff2_habitat_moz <- ff2_habitat_moz %>%
  mutate(`Benthic attribute *` = case_when(
    is.na(genus) & is.na(species) ~ NA_character_,
    is.na(genus) ~ species,
    is.na(species) ~ genus,
    TRUE ~ paste(genus, species)
  ))

# Column Methodology
ff2_habitat_moz <- ff2_habitat_moz %>%
  rename(`Methodology *` = methodology)

selected_ff2_habitat_moz <- ff2_habitat_moz %>%
  select(
    "Methodology *",
    "Site *",
    "Management *",
    "Sample date: Year *",
    "Sample date: Month *",
    "Sample date: Day *",
    "Depth *",
    "Transect number *",
    "Benthic attribute *")

##########

## NAs counts in required fields:
na_counts_moz <- ff2_habitat_moz %>%
  summarise(
    `Management *` = sum(is.na(`Management *`)),
    `Sample date: Year *` = sum(is.na(`Sample date: Year *`)),
    `Sample date: Month *` = sum(is.na(`Sample date: Month *`)),
    `Sample date: Day *` = sum(is.na(`Sample date: Day *`)),
    `Depth *` = sum(is.na(`Depth *`)),
    `Transect number *` = sum(is.na(`Transect number *`)),
    `Benthic attribute *` = sum(is.na(`Benthic attribute *`))
  )




##########

## Need to address: Methodology, Depth, Benthic Attribute !!! 

# Excel Output: 
#folder_path <- here("data", "preprocessed", "mozambique", "ff2.0") #NAs left --> Preprocessed Folder
#file_path <- file.path(folder_path, "moz_ff2.0_habitat_preprocessed.xlsx")
#write_xlsx(selected_ff2_habitat_moz, file_path)


```


## Sites

### FF 2.0 Fish

```{r}
# Site = location name or ma + location name ???

# Get unique sites (location_name)
ff2_fish_moz_sites <- ff2_fish_moz %>%
  group_by(`Site *`, lat, lon, `Management *`) %>%
  summarise(Count = n(), .groups = "drop")%>%
  arrange(desc(Count))


# Check for locations with the same name but different latitudes or longitudes
locations_with_different_coords_moz <- ff2_fish_moz %>%
  group_by(`Site *`) %>%
  summarise(
    Unique_Lats = n_distinct(lat),
    Unique_Lons = n_distinct(lon),
    .groups = "drop") %>%
  filter(Unique_Lats > 1 | Unique_Lons > 1) # Filter for locations with more than one unique latitude or longitude


distinct_coords_for_varied_locations_moz <- ff2_fish_moz %>%
  group_by(`Site *`) %>%
  distinct(`Site *`, lat, lon) %>%
  ungroup() %>%
  arrange(`Site *`, lat, lon)

# Filter to keep only those locations with more than one unique combination of latitude and longitude
locations_with_different_coords_moz_detail <- distinct_coords_for_varied_locations_moz %>%
  add_count(`Site *`) %>%
  filter(n > 1) %>%
  select(-n) # remove the count column after filtering


# Function to calculate the central point (mean lat and lon) for each site
central_point <- function(df) {
  central_points <- df %>%
    group_by(`Site *`) %>%
    summarise(
      mean_lat = mean(lat, na.rm = TRUE),
      mean_lon = mean(lon, na.rm = TRUE)
    )
  
  return(central_points)
}

# Applying the function
central_point_moz <- central_point(ff2_fish_moz)

# Merge the central points
ff2_fish_moz_sites_management <- central_point_moz %>%
  left_join(ff2_fish_moz %>% select(`Site *`, `country`, `Management *`) %>% distinct(), by = "Site *")

# Clean Sites
selected_ff2_fish_moz_sites <- ff2_fish_moz_sites_management %>%
  select(
    name = `Site *`,
    latitude = mean_lat,
    longitude = mean_lon,
    country = country) %>%
  mutate(
    notes = NA,
    reef_type = NA,
    reef_zone = NA,
    exposure = NA) %>%
  filter(name != "Test") #remove test or add lat and lon?



# Filter MERMAID Sites country == "Mozambique"
sites_mermaid_moz <- sites_mermaid %>%
  filter(country == "Mozambique") #No observations for Mozambique!

# Add the MA name to make it easier for the country teams to update the information
  # Fish
sites_moz_fish <- selected_ff2_fish_moz_sites %>%
  left_join(ff2_fish %>% select(location_name, ma_name), by = c("name" = "location_name")) %>%
  distinct(name, .keep_all = TRUE) %>% 
  select(ma_name, name, latitude, longitude, country, reef_type, reef_zone, exposure) %>% 
  arrange(ma_name)%>% 
  rename(reef_exposure = exposure)
    # Cleaning location names
sites_moz_fish <- sites_moz_fish %>%
  mutate(name = tolower(name)) %>% #All to lowercase to avoid duplicates based on using uppercase 
  mutate(name = gsub(" ", "_", name)) %>% #Change spaces to _ to avoid duplicates
  distinct(name, .keep_all = TRUE)


# Excel Output: 
#folder_path <- here("data", "preprocessed", "mozambique", "ff2.0") #NAs left --> Preprocessed Folder
#file_path <- file.path(folder_path, "moz_ff2.0_fish_sites_preprocessed.xlsx")
#write_xlsx(sites_moz_fish, file_path)

```

### FF 2.0 Habitat

```{r}
## Filter country == "Mozambique"
ff2_habitat_moz <- ff2_habitat %>%
  filter(country == "Mozambique")

ff2_fish_moz <- ff2_fish %>%
  filter(country == "Mozambique")


##########

# Get unique sites (location_name)
ff2_habitat_moz_sites <- ff2_habitat_moz %>%
  group_by(location_name, lat, lon, location_status) %>%
  summarise(Count = n(), .groups = "drop")%>%
  arrange(desc(Count))

ff2_fish_moz_sites <- ff2_fish_moz %>%
  group_by(location_name, lat, lon, location_status) %>%
  summarise(Count = n(), .groups = "drop")%>%
  arrange(desc(Count))

# Check for locations with the same name but different latitudes or longitudes
locations_with_different_coords_moz <- ff2_habitat_moz %>%
  group_by(location_name) %>%
  summarise(
    Unique_Lats = n_distinct(lat),
    Unique_Lons = n_distinct(lon),
    .groups = "drop") %>%
  filter(Unique_Lats > 1 | Unique_Lons > 1) # Filter for locations with more than one unique latitude or longitude


# Check if sites from FF2.0_habitat match sites from FF2.0_fish
unique_habitat_moz_sites <- setdiff(ff2_habitat_moz_sites$location_name, ff2_fish_moz_sites$location_name)

if(length(unique_habitat_moz_sites) > 0) {
  print("Sites present in ff2_habitat but not in ff2_fish:")
  print(unique_habitat_moz_sites)
} else {
  print("All sites in ff2_habitat are also present in ff2_fish.")
}


##########

# Check for the most similar site of FF2.0_fish for the unique sites in FF2.0_habitat

# Prepare an empty dataframe to store results
results_moz <- data.frame(unique_site_habitat = character(), closest_match_fish = character(), stringsAsFactors = FALSE)
# Loop through each unique site to find the closest match
for(site in unique_habitat_moz_sites) {
  distances <- stringdist::stringdist(site, ff2_fish_moz_sites$location_name) # Calculate the string distance
  min_distance_index <- which.min(distances)  # Find the index of the minimum distance
  closest_match <- ff2_fish_moz_sites$location_name[min_distance_index] # Find the closest matching site name
  results_moz <- rbind(results_moz, data.frame(unique_site_habitat = site, closest_match_fish = closest_match)) # Add to the results dataframe
}



##########

# Clean Sites
selected_ff2_habitat_moz_sites <- ff2_habitat_moz_sites %>%
  select(
    name = location_name,
    latitude = lat,
    longitude = lon,
    management = location_status) %>%
  mutate(
    country = "Mozambique",
    notes = NA,
    reef_type = NA,
    reef_zone = NA,
    exposure = NA)



# Habitat
sites_moz_habitat <- selected_ff2_habitat_moz_sites %>%
  left_join(ff2_habitat %>% select(location_name, sitename), by = c("name" = "location_name")) %>%
  distinct(name, .keep_all = TRUE) %>% 
  select(sitename, name, latitude, longitude, country, reef_type, reef_zone, exposure) %>% 
  arrange(sitename)%>%
  rename(site_name = sitename) %>% 
  rename(reef_exposure = exposure)
    # Cleaning location names
sites_moz_habitat <- sites_moz_habitat %>%
  mutate(name = tolower(name)) %>% #All to lowercase to avoid duplicates based on using uppercase 
  mutate(name = gsub(" ", "_", name)) %>% #Change spaces to _ to avoid duplicates
  distinct(name, .keep_all = TRUE)


# Excel Output: 
#folder_path <- here("data", "preprocessed", "mozambique", "ff2.0") #NAs left --> Preprocessed Folder
#file_path <- file.path(folder_path, "moz_ff2.0_habitat_sites_preprocessed.xlsx")
#write_xlsx(sites_moz_habitat, file_path)

```

