---
title: "migrate_hon_ff2.0_fish"
author: "Mariano Viz"
date: "2025-06-06"
output: html_document
---

# Migrating Sites


```{r}

# Read in the fish sites data
fish_sites <- read_excel(here("data", "processed", "honduras", "ff2.0", "hon_ff2.0_fish_sites_processed.xlsx"))


# Get project for import
project <- mermaid_search_my_projects("honduras_ff2.0_fish", include_test_projects = TRUE)


# Sites
fish_sites <- fish_sites %>%
  select(name, latitude, longitude, country, reef_type, reef_zone, reef_exposure) %>%
  mutate(notes = NA) %>%
  rename(exposure = reef_exposure)


# Import
fish_sites %>%
 mermaid_import_project_sites(project)


```

# Migrating Data


### 1. Download the MERMAID Template


```{r}
# Access your MERMAID projects by using mermaid_search_my_projects() with the project name
project <- mermaid_search_my_projects("honduras_ff2.0_fish", include_test_projects = TRUE)

# Get the fish belt MERMAID template and options using mermaid_import_get_template_and_options() and save it to a file (in this case called fishbelt_mermaid_template.xlsx and benthicpit_mermaid_template.xlsx)
fish_template_and_options <- mermaid_import_get_template_and_options( 
  project,
  "fishbelt",
  "fishbelt_mermaid_template.xlsx")



```


### 2. Reformat the data to match the template

```{r}
# Reading ind_ff2.0_fish_processed.xlsx
fish_data <- read_excel(here("data", "processed", "honduras", "ff2.0", "hon_ff2.0_fish_processed.xlsx"))


# Update sites to lowercase for fish and convert "Transect number *" to numeric
fish_data <- fish_data %>%
  mutate(
    `Site *` = str_replace_all(str_to_lower(`Site *`), " ", "_"),
    `Transect number *` = as.numeric(`Transect number *`)
  )

```


### 3. Address errors and warnings


```{r}
mermaid_import_check_options(fish_data, fish_template_and_options, "Site *")
fish_data <- fish_data %>%
  filter(!`Site *` %in% c("dive_site_1", "test"))

mermaid_import_check_options(fish_data, fish_template_and_options, "Management *")

mermaid_import_check_options(fish_data, fish_template_and_options, "Sample date: Year *")

mermaid_import_check_options(fish_data, fish_template_and_options, "Sample date: Month *")

mermaid_import_check_options(fish_data, fish_template_and_options,"Sample date: Day *")

mermaid_import_check_options(fish_data, fish_template_and_options,"Depth *")
fish_data <- fish_data %>%
  mutate(`Depth *` = round(`Depth *`, 1))
         
mermaid_import_check_options(fish_data, fish_template_and_options,"Transect number *")
         
mermaid_import_check_options(fish_data, fish_template_and_options,"Transect length surveyed *")
         
mermaid_import_check_options(fish_data, fish_template_and_options,"Width *")
        
mermaid_import_check_options(fish_data, fish_template_and_options,"Fish size bin *")
         
mermaid_import_check_options(fish_data, fish_template_and_options,"Observer emails *")
         
mermaid_import_check_options(fish_data, fish_template_and_options,"Fish name *")

  # Remove sp. 
  fish_data$`Fish name *` <- gsub(" sp\\.$", "", fish_data$`Fish name *`)
  
  
  # Get closest choice: 
  fish_name <- mermaid_import_check_options(fish_data, fish_template_and_options,"Fish name *") %>% 
    filter(match == "FALSE")
 
  # Renaming Fish Species
     # Left join to add the closest_choice to fish_data
    fish_data <- fish_data %>%
    left_join(fish_name, by = c("Fish name *" = "data_value"))

   # Replace the values in 'Fish name *' with 'closest_choice' where applicable
   fish_data$`Fish name *` <- ifelse(!is.na(fish_data$closest_choice), fish_data$closest_choice, fish_data$`Fish name *`)

    # Remove the 'closest_choice' and 'match' column if you no longer need it
    fish_data <- fish_data %>% select(-closest_choice)
    fish_data <- fish_data %>% select(-match)


mermaid_import_check_options(fish_data, fish_template_and_options,"Size *")
fish_data <- fish_data %>%
  mutate(`Size *` = round(`Size *`, 1))
         
mermaid_import_check_options(fish_data, fish_template_and_options,"Count *")
fish_data <- fish_data %>%
  filter(`Count *` != 0)

# Clean Data

write_csv(fish_data, "fishbelt_clean.csv")

```

### 4. Import (ingest) data to MERMAID


```{r}
# “Dry run” before actually ingesting to check the data:
mermaid_import_project_data(
  fish_data,
  project,
  method = "fishbelt",
  dryrun = TRUE
)




# Ingesting data:
# mermaid_import_project_data(
# fish_data,
# project,
# method = "fishbelt",
# dryrun = FALSE
# )


```




